# vim ft=yaml

# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4

virtualenv:
    system_site_packages: true

before_install:
    - export DISPLAY=:99.0
    - export SPACER="\n\n\n\n\n\n\n\n\n\n*************************\n\n"
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get update

    - travis_retry pip install wheel flake8 coveralls
    - travis_retry pip install --no-index --find-links=http://wheels.scikit-image.org/ -r requirements.txt
    - python check_bento_build.py


install:
    - tools/header.py "Dependency versions"
    - tools/build_versions.py
    - export PYTHONWARNINGS=all
    - python setup.py build_ext --inplace

    # Matplotlib settings
    - export MPL_DIR=$HOME/.config/matplotlib
    - mkdir -p $MPL_DIR
    - touch $MPL_DIR/matplotlibrc
    - "echo 'backend : Agg' > $MPL_DIR/matplotlibrc"
    - "echo 'backend.qt4 : PySide' >> $MPL_DIR/matplotlibrc"

script:
    # Run all tests with minimum dependencies
    - nosetests --exe -v skimage

    - echo -e $SPACER

    # Run pep8 and flake tests
    - flake8 --exit-zero --exclude=test_*,six.py skimage doc/examples viewer_examples

    - echo -e $SPACER

    - travis_retry pip install networkx
    - travis_retry pip install --no-index --find-links=http://wheels.scikit-image.org/ PySide

    # - pyfits and imread do NOT support py3.2
    - if [[  $TRAVIS_PYTHON_VERSION != 3.2 ]]; then
        sudo apt-get install libtiff4-dev libwebp-dev xcftools;
        travis_retry pip install imread;
        travis_retry pip install pyfits;
      fi
    # TODO: update when SimpleITK become available on py34 or hopefully pip
    - if [[  $TRAVIS_PYTHON_VERSION != 3.4 ]]; then
        travis_retry easy_install SimpleITK;
      fi

    - echo -e $SPACER

    # Run all doc examples
    - export PYTHONPATH=$(pwd):$PYTHONPATH
    - for f in doc/examples/*.py; do python "$f"; if [ $? -ne 0 ]; then exit 1; fi done
    - for f in doc/examples/applications/*.py; do python "$f"; if [ $? -ne 0 ]; then exit 1; fi done

    - echo -e $SPACER

    # run tests again with optional dependencies to get more coverage
    # measure coverage on py3.3
    - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then
         nosetests --exe -v --with-doctest --with-cov --cover-package skimage;
      else
         nosetests --exe -v --with-doctest skimage;
      fi

after_success:
    - coveralls;
